#!/usr/bin/env node
// ============================================================================
// Phase 5 — Local Offline Verifier Example
// ----------------------------------------------------------------------------
// Demonstrates offline proof verification using production VK without network access.
// Requires no secrets; uses only public artifacts.
// ============================================================================

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import snarkjs from "snarkjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.join(__dirname, "..", "..");

async function main() {
  console.log("=== AegisProof Local Verifier (Offline Mode) ===\n");

  // Load production VK
  const vkeyPath = path.join(ROOT, "artifacts/phase4/final/production-vkey.json");
  if (!fs.existsSync(vkeyPath)) {
    throw new Error(`Missing production VK: ${vkeyPath}. Ensure Phase 4 ceremony completed.`);
  }
  const vkey = JSON.parse(fs.readFileSync(vkeyPath, "utf8"));
  console.log(`✓ Loaded production VK: ${vkey.groth16 ? "Groth16" : "Unknown format"}`);

  // Verify IC count matches expected (31 for Groth16 with vk_alpha_1 included)
  const icCount = vkey.IC?.length || 0;
  if (icCount !== 31) {
    throw new Error(`Unexpected IC count: ${icCount} (expected 31)`);
  }
  console.log(`✓ IC constants verified: ${icCount}/31 points`);

  // Load production proof (generated by phase4_verify_production.mjs)
  const proofPath = path.join(ROOT, "artifacts/phase4/reports/production_proof_baseline.json");
  if (!fs.existsSync(proofPath)) {
    throw new Error(`Missing baseline proof: ${proofPath}. Run scripts/phase4_verify_production.mjs first.`);
  }

  const data = JSON.parse(fs.readFileSync(proofPath, "utf8"));
  const proof = typeof data === "string" ? JSON.parse(data) : data;

  // Handle both old/new proof formats
  const pubSignals = Array.isArray(data.publicSignals)
    ? data.publicSignals.map((x) => x.toString())
    : (data.publicSignals || []).map((x) => x.toString());

  const grothProof = proof.proof || proof;
  if (!grothProof.pi_a || !grothProof.pi_b || !grothProof.pi_c) {
    throw new Error("Invalid proof structure: missing pi_a/pi_b/pi_c");
  }

  console.log(`✓ Loaded proof (${grothProof.pi_a.length} A, ${grothProof.pi_b[0].length * 2} B, ${grothProof.pi_c.length} C)`);
  console.log(`✓ Public signals: ${pubSignals.length}`);

  // Off-chain verification (no network required)
  const startTime = Date.now();
  const ok = await snarkjs.groth16.verify(vkey, pubSignals, grothProof);
  const durationMs = Date.now() - startTime;

  if (!ok) {
    console.error("✗ VERIFICATION FAILED");
    process.exit(1);
  }

  console.log(`✓ OFF-CHAIN VERIFICATION SUCCESSFUL (${durationMs}ms)`);

  // Signal inspection (read-only, non-authoritative)
  if (pubSignals.length >= 30) {
    console.log("\nPublic Signals (first 10):");
    for (let i = 0; i < Math.min(10, pubSignals.length); i++) {
      console.log(`  [${i}] ${pubSignals[i].slice(0, 16)}...`);
    }
  }

  console.log("\n=== Local Verifier Complete ===");
  console.log("This example does NOT perform any deployments or modify state.");
  console.log("All artifacts are read-only and can be audited independently.");
  process.exit(0);
}

main().catch((err) => {
  console.error("Fatal:", err.message);
  process.exit(1);
});
