// ============================================================================
// Example 1: Complete proof verification workflow
// ============================================================================
import fs from "fs";
import { createPublicClient, http } from "viem";
import * as sdk from "../src/core.ts";

async function main() {
  console.log("=== AegisProof SDK Example: Verify On-Chain ===\n");

  // Load proof from production artifact (generated by scripts/phase4_verify_production.mjs)
  const proofData = JSON.parse(fs.readFileSync("artifacts/phase4/reports/production_proof_baseline.json", "utf8"));
  
  console.log("[1] Loaded proof from file");
  
  // Extract proof structure
  const proof = typeof proofData.proof !== "undefined" ? proofData.proof : proofData;
  const signals = Array.isArray(proofData.publicSignals) 
    ? proofData.publicSignals.map((s) => s.toString()) 
    : [];
  
  console.log(`[2] Extracted proof (A:${proof.pi_a.length}, B:${proof.pi_b[0].length * 2}, C:${proof.pi_c.length})`);
  console.log(`[3] Public signals count: ${signals.length}`);
  
  // Build client for Ethereum mainnet (replace with actual RPC)
  const client = createPublicClient({
    transport: http(),
  });
  
  // Use production verifier address (deploy via deployment-mainnet.md instructions)
  const verifierAddress = "0xYourVerifierContractAddress";
  
  try {
    console.log("\n[4] Validating signal count...");
    sdk.validateSignalCount(signals);
    console.log("✓ Signal count validated (30 signals)");
    
    console.log("\n[5] Converting to calldata format...");
    const calldata = sdk.toCalldataSignals(signals);
    console.log("✓ Calldata generated");
    
    console.log("\n[6] Converting proof to Solidity format...");
    const proofCalldata = sdk.grothProofToCalldata(proof);
    console.log("✓ G2 coordinates swapped correctly");
    
    console.log("\n[7] Estimating gas cost...");
    const gasEstimate = await sdk.estimateVerifyGas(client, verifierAddress, proof, signals);
    console.log(`✓ Estimated gas: ${gasEstimate.toString()} wei`);
    
    console.log("\n[8] Performing off-chain simulation...");
    const result = await sdk.offChainVerify(client, verifierAddress, proof, signals);
    console.log(result.success ? "✓ Simulation passed" : "✗ Simulation failed");
    
    console.log("\n=== Example Complete ===");
    console.log("Note: Replace verifierAddress with deployed contract.");
    console.log("      Use real RPC endpoint for actual on-chain verification.");
    
  } catch (error) {
    if (error instanceof sdk.AegisSDKError) {
      console.error(`\n[${error.code}] ${error.message}`);
      if (error.context) {
        console.error("Context:", JSON.stringify(error.context, null, 2));
      }
    } else {
      console.error("\nUnexpected error:", error.message);
    }
    process.exit(1);
  }
}

main().catch(console.error);
